version: '3.6'
services:
  node:
    image: node:14-alpine3.17
    # platform: linux/amd64
    working_dir: "/home/node/touch-desktop"
    # command: apk add git dpkg fakeroot rpm
    entrypoint: /home/node/touch-desktop/entrypoint.sh
    environment:
      YARN_CACHE_DIR: /home/node/.cache/yarn
    volumes:
      - .:/home/node/touch-desktop
      - ${HOME}/.cache:/home/node/.cache
      - ${HOME}/.cache:/root/.cache
      - ${HOME}/.ssh:/home/node/.ssh/.ssh:ro
      - ${HOME}/.ssh:/root/.ssh/.ssh:ro

